#!/bin/bash

docker compose -f compose/compose.yaml up -d dbpostgres

mvn clean install 

docker compose -f compose/compose.yaml down -d dbpostgres

docker compose -f compose/compose.yaml up -d 
#docker compose/compose up -d --remove-orphans